when:
  - event: push
    branch: dev

steps:
  - name: build
    image: flutter
    commands:
      - echo "Starting to build..."
      - git clone https://git.mrdab.vore.media/ThatOneJackalGuy/OpenContacts.git
      - cd ./OpenContacts
  - name: a-test-step
    image: golang:1.16
    commands:
      - echo "Testing ..."
      - ./executable