when:
  - event: push
    branch: dev

steps:
  - name: build
    image: instrumentisto/flutter
    commands:
      - cd OpenContacts
      - echo "Starting to build..."
      - flutter build --debug
    when:
      status: failure
        - echo "Build failed! Consult with maintainer."