when:
  - event: push
    branch: dev

steps:
  - name: build
    image: ubuntu
    commands:
      - apt-get install -y curl git unzip xz-utils zip libglu1-mesa
      - vim's installed
  - name: a-test-step
    image: golang:1.16
    commands:
      - echo "Testing ..."
      - ./executable